services:

  lab:
    # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
    build: .
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    ports:
    # left is your machine, right is dockers, if you want to change, also add a --port=**** arg to the command line here
      - "8888:8888"
    env_file:
       - ./.env   
    environment:
      - JUPYTER_ENABLE_LAB=1
      - GRANT_SUDO=yes
    command: start.sh jupyter lab